# Spring Application Name
spring.application.name=saludya-backend

# Default to development when no explicit profile is provided.
spring.profiles.default=dev

# Shared Spring Data JPA Hibernate Configuration
spring.jpa.hibernate.naming.physical-strategy=com.ruwalabs.saludya.shared.infrastructure.persistence.jpa.configuration.strategy.SnakeCaseWithPluralizedTablePhysicalNamingStrategy

# Application Information for Documentation
documentation.application.description=@project.description@
documentation.application.version=@project.version@

# JWT Configuration Properties
application.jwt.secret=4S3cReTK1puB4ck3ndS3cur1tyK3yTh4tIsSuFf1c13ntlyL0ng4ndStr0ng!
application.jwt.expiration-ms=86400000

# i18n message bundles
spring.messages.basename=messages
spring.messages.encoding=UTF-8

# Flyway Configuration
spring.flyway.enabled=false

# Show SQL queries in the console for debugging
spring.jpa.show-sql=true

# SMTP Gmail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=rupwalabs@gmail.com
spring.mail.password=xxxx xxxx xxxx xxxx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Cloudinary Configuration
cloudinary.cloud-name=xxxxxxxxx
cloudinary.api-key=xxxxxxxxxxxxx
cloudinary.api-secret=xxxxxxxxxxxxxxxxxxxxxxxxxxxxx