package com.ruwalabs.saludya.arrivalcheckin.infrastructure.tokens.jwt;

import com.ruwalabs.saludya.arrivalcheckin.application.internal.outboundservices.acl.QrTokenPayload;
import com.ruwalabs.saludya.arrivalcheckin.application.internal.outboundservices.acl.QrTokenService;
import io.jsonwebtoken.Jwts;
import io.jsonwebtoken.security.Keys;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

import javax.crypto.SecretKey;
import java.nio.charset.StandardCharsets;
import java.time.Instant;
import java.util.Date;
import java.util.Optional;

/**
 * JJWT-based implementation of {@link QrTokenService}.
 *
 * <p>The QR token is a signed JWT generated by the backend itself (no external
 * QR service). The scanner only forwards the raw string; validation happens here.</p>
 */
@Service
@Slf4j
public class JwtQRValidator implements QrTokenService {

    private static final String TIME_SLOT_CLAIM = "timeSlotId";

    @Value("${application.qr.secret}")
    private String secret;

    @Value("${application.qr.expiration-ms}")
    private long expirationMs;

    @Override
    public String generateQrToken(Long appointmentId, Long timeSlotId) {
        var now = Instant.now();
        var builder = Jwts.builder()
                .subject(String.valueOf(appointmentId))
                .issuedAt(Date.from(now))
                .expiration(Date.from(now.plusMillis(expirationMs)));
        if (timeSlotId != null) {
            builder.claim(TIME_SLOT_CLAIM, timeSlotId);
        }
        return builder.signWith(getSigningKey()).compact();
    }

    @Override
    public Optional<QrTokenPayload> validateQrToken(String token) {
        try {
            var claims = Jwts.parser()
                    .verifyWith(getSigningKey())
                    .build()
                    .parseSignedClaims(token)
                    .getPayload();
            var appointmentId = Long.valueOf(claims.getSubject());
            var timeSlotClaim = claims.get(TIME_SLOT_CLAIM);
            var timeSlotId = timeSlotClaim == null ? null : ((Number) timeSlotClaim).longValue();
            return Optional.of(new QrTokenPayload(appointmentId, timeSlotId));
        } catch (Exception ex) {
            log.warn("Invalid QR token: {}", ex.getMessage());
            return Optional.empty();
        }
    }

    private SecretKey getSigningKey() {
        return Keys.hmacShaKeyFor(secret.getBytes(StandardCharsets.UTF_8));
    }
}
